[package]
name = "monica-application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
monica-domain.workspace = true
anyhow.workspace = true
futures-util = { workspace = true, features = ["alloc"] }
log.workspace = true
serde = { workspace = true, features = ["derive"] }
strum.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt"] }
