[package]
name = "monica-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
monica-application.workspace = true
monica-domain.workspace = true
monica-settings.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
specta = { workspace = true, features = ["derive", "serde_json"] }
specta-typescript.workspace = true
