[package]
name = "monica-adapters"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
monica-application.workspace = true
monica-domain.workspace = true
monica-paths.workspace = true
anyhow.workspace = true
log.workspace = true
octocrab.workspace = true
reqwest.workspace = true
rustls.workspace = true
scraper.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
tokio = { workspace = true, features = ["rt"] }
uuid.workspace = true

[dev-dependencies]
ctor.workspace = true
monica-storage-sqlite.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }
