// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
  /**  Deliberately sync: NSPasteboard requires the main thread. Do NOT wrap in `off_main`. */
  clipboardWriteImage: (path: string) =>
    typedError<null, ApiError>(__TAURI_INVOKE("clipboard_write_image", { path })),
  /**
   *  Resolve each candidate against `cwd` (expanding a leading `~`) and return the
   *  canonical absolute path when it exists, or `null` otherwise. `canonicalize`
   *  doubles as the existence check: a path that cannot be resolved on disk is
   *  dropped, so the frontend only ever highlights real files.
   */
  resolveEditorPaths: (cwd: string, candidates: string[]) =>
    typedError<(string | null)[], ApiError>(
      __TAURI_INVOKE("resolve_editor_paths", { cwd, candidates }),
    ),
  openInEditor: (path: string) =>
    typedError<null, ApiError>(__TAURI_INVOKE("open_in_editor", { path })),
  worktreeInfo: (cwd: string) =>
    typedError<
      {
        repo: string;
        branch: string;
      } | null,
      ApiError
    >(__TAURI_INVOKE("worktree_info", { cwd })),
  terminalCreateSession: (
    runspaceId: string,
    tabId: string,
    kind: TerminalSessionKind,
    cwd: string,
    rows: number,
    cols: number,
    env: [string, string][] | null,
  ) =>
    typedError<TerminalSession, ApiError>(
      __TAURI_INVOKE("terminal_create_session", { runspaceId, tabId, kind, cwd, rows, cols, env }),
    ),
  terminalAttach: (sessionId: string, replayBytes: number | null) =>
    typedError<AttachResult, ApiError>(
      __TAURI_INVOKE("terminal_attach", { sessionId, replayBytes }),
    ),
  terminalDetach: (sessionId: string) =>
    typedError<null, ApiError>(__TAURI_INVOKE("terminal_detach", { sessionId })),
  terminalWrite: (sessionId: string, data: string) =>
    typedError<null, ApiError>(__TAURI_INVOKE("terminal_write", { sessionId, data })),
  terminalResize: (sessionId: string, rows: number, cols: number) =>
    typedError<null, ApiError>(__TAURI_INVOKE("terminal_resize", { sessionId, rows, cols })),
  terminalTerminate: (sessionId: string) =>
    typedError<null, ApiError>(__TAURI_INVOKE("terminal_terminate", { sessionId })),
  terminalListSessions: (runspaceId: string | null) =>
    typedError<TerminalSession[], ApiError>(
      __TAURI_INVOKE("terminal_list_sessions", { runspaceId }),
    ),
  terminalLoadState: (windowLabel: string) =>
    typedError<TerminalStateSnapshot, ApiError>(
      __TAURI_INVOKE("terminal_load_state", { windowLabel }),
    ),
  terminalSaveState: (windowLabel: string, state: TerminalStateSnapshot) =>
    typedError<null, ApiError>(__TAURI_INVOKE("terminal_save_state", { windowLabel, state })),
  listTaskSummaries: (project: string | null) =>
    typedError<TaskSummaryRow[], ApiError>(__TAURI_INVOKE("list_task_summaries", { project })),
  getBoardColumns: () => __TAURI_INVOKE<BoardColumn[]>("get_board_columns"),
  trackGithubIssue: (input: string) =>
    typedError<TaskCreated, ApiError>(__TAURI_INVOKE("track_github_issue", { input })),
  listProjects: () => typedError<ProjectOption[], ApiError>(__TAURI_INVOKE("list_projects")),
  createRawTask: (title: string, projectId: string) =>
    typedError<TaskCreated, ApiError>(__TAURI_INVOKE("create_raw_task", { title, projectId })),
  listBenchRunspaceMap: () =>
    typedError<[string, string][], ApiError>(__TAURI_INVOKE("list_bench_runspace_map")),
  taskShellEnv: (taskId: string) =>
    typedError<[string, string][], ApiError>(__TAURI_INVOKE("task_shell_env", { taskId })),
  openBench: (taskId: string) =>
    typedError<TaskBench, ApiError>(__TAURI_INVOKE("open_bench", { taskId })),
  prepareTask: (taskId: string) =>
    typedError<PrepareTaskResult, ApiError>(__TAURI_INVOKE("prepare_task", { taskId })),
  runTask: (taskId: string, agent: "claude" | "codex" | null) =>
    typedError<RunTaskResult, ApiError>(__TAURI_INVOKE("run_task", { taskId, agent })),
  closeTask: (taskId: string) =>
    typedError<null, ApiError>(__TAURI_INVOKE("close_task", { taskId })),
  /**
   *  Promote the run living in the given Workbench tab to its task's Main Run. Returns whether the
   *  primary actually changed; `false` covers "no run in this tab", "already main" and "primary is
   *  mid-prepare" so the shortcut can stay a silent no-op.
   */
  makeMainTaskRun: (tabId: string) =>
    typedError<boolean, ApiError>(__TAURI_INVOKE("make_main_task_run", { tabId })),
  primaryTabId: (taskId: string) =>
    typedError<string | null, ApiError>(__TAURI_INVOKE("primary_tab_id", { taskId })),
  listNotebooks: () => typedError<NotebookSummary[], ApiError>(__TAURI_INVOKE("list_notebooks")),
  getNotebookPages: (notebookId: string) =>
    typedError<NotebookPageRow[], ApiError>(__TAURI_INVOKE("get_notebook_pages", { notebookId })),
  /**
   *  Read the plan held by the run driving the given Workbench tab. `Ok(None)` covers a shell tab, a
   *  run that never planned, and a plan file since deleted — all "nothing to preview" to the caller.
   */
  readRunspacePlan: (terminalTabId: string) =>
    typedError<
      {
        /**  Absolute path of the plan file (`~/.claude/plans/<name>.md`). */
        path: string;
        /**  File name only, for the preview header. */
        file_name: string;
        /**  Markdown source of the plan. */
        body: string;
      } | null,
      ApiError
    >(__TAURI_INVOKE("read_runspace_plan", { terminalTabId })),
  forceSyncPullRequests: () =>
    typedError<null, ApiError>(__TAURI_INVOKE("force_sync_pull_requests")),
  /**
   *  The persisted Claude session mappings, with liveness reconciled against the daemon
   *  first — startup recovery adopts the rows still `active` as Workbench tabs.
   */
  claudeListSessions: () =>
    typedError<ClaudeSession[], ApiError>(__TAURI_INVOKE("claude_list_sessions")),
  openNamedWindow: (label: string) =>
    typedError<null, ApiError>(__TAURI_INVOKE("open_named_window", { label })),
};

/** Events */
export const events = {
  claudeSessionMessage: makeEvent<ClaudeSessionMessage>("claude-session:message"),
  claudeSessionOpened: makeEvent<ClaudeSessionOpened>("claude-session:opened"),
  claudeSessionStateChanged: makeEvent<ClaudeSessionStateChanged>("claude-session:state-changed"),
  prSyncCompleted: makeEvent<PrSyncCompleted>("pr-sync:completed"),
  taskRunStatusChanged: makeEvent<TaskRunStatusChanged>("task-run:status-changed"),
};

/* Types */
export type Agent = "claude" | "codex";

/**
 *  The error half of every Tauri command result. Replaces the previous `Result<T, String>` so the
 *  frontend receives a structured `{ code, message }` instead of an opaque string.
 */
export type ApiError = {
  code: ApiErrorCode;
  message: string;
};

/**
 *  Machine-readable category for an error crossing the Tauri boundary. The frontend branches on
 *  `code` (e.g. show a "not found" vs. "already in progress" surface) instead of string-matching.
 */
export type ApiErrorCode =
  | "not_found"
  | "conflict"
  | "validation"
  | "authentication_required"
  | "storage"
  | "external"
  | "indeterminate";

export type AttachResult = {
  /**  Base64 transcript tail to write into xterm before streaming live output. */
  replay: string;
  rows: number;
  cols: number;
};

export type BoardColumn = {
  key: string;
  label: string;
  statuses: DisplayStatus[];
};

export type ClaudeConversationStatus = "idle" | "thinking" | "awaiting_user";

/**
 *  The durable mapping for a Claude Code session Monica launched: which Workbench
 *  runspace/tab hosts it, which terminal session drives its PTY, and the cwd its JSONL
 *  transcript path derives from.
 */
export type ClaudeSession = {
  claude_session_id: string;
  runspace_id: string;
  tab_id: string;
  terminal_session_id: string;
  cwd: string;
  name: string | null;
  status: ClaudeSessionStatus;
  conversation_status: ClaudeConversationStatus;
  wait_reason: TaskRunWaitReason | null;
  created_at: string;
  ended_at: string | null;
};

/**  New transcript records (assistant text / tool uses) read after a completed turn. */
export type ClaudeSessionMessage = {
  claude_session_id: string;
  records: ClaudeTranscriptRecord[];
};

/**
 *  Announces an Agent Runtime-created terminal session so the Workbench can adopt a tab bound to it.
 *  Purely observational: the session row, PTY spawn, and Claude launch are already handled
 *  backend-side by the time this fires.
 */
export type ClaudeSessionOpened = {
  runspace_id: string;
  tab_id: string;
  session_id: string;
  cwd: string;
  title: string | null;
};

/**
 *  A Claude Runtime session's observable state moved (hook-driven): the conversation
 *  went idle/thinking/awaiting-user, or the session ended.
 */
export type ClaudeSessionStateChanged = {
  claude_session_id: string;
  tab_id: string;
  session_status: ClaudeSessionStatus;
  conversation_status: ClaudeConversationStatus;
  wait_reason: TaskRunWaitReason | null;
};

export type ClaudeSessionStatus = "pending" | "active" | "ended";

export type ClaudeToolUse = {
  id: string;
  name: string;
  input_json: string;
};

export type ClaudeTranscriptRecord = {
  uuid: string | null;
  timestamp: string | null;
} & ClaudeTranscriptRecordKind;

/**  One transcript record surfaced to the frontend (assistant text / tool uses). */
export type ClaudeTranscriptRecordKind =
  | { kind: "assistant"; text: string; tool_uses: ClaudeToolUse[] }
  | { kind: "user" }
  | { kind: "other" };

export type DisplayStatus =
  | "ready"
  | "in_progress"
  | "setting_up"
  | "prepared"
  | "running"
  | "waiting_for_user"
  | "stopped"
  | "failed"
  | "closed";

export type GithubPullRequestRef = {
  repo: string | null;
  number: number | null;
  url: string | null;
  status: string | null;
  is_open_or_draft: boolean;
};

export type NotebookPageRow = {
  id: string;
  title: string;
  /**  Outline number (`1`, `1.1`, …) — the page's place in the document tree. */
  number: string;
  /**  Raw `created` front matter value (ISO 8601), if present. */
  created: string | null;
  /**  Page body (front matter stripped) — the markdown source. */
  body: string;
};

export type NotebookSummary = {
  id: string;
  title: string;
  page_count: number;
};

export type PlanPreview = {
  /**  Absolute path of the plan file (`~/.claude/plans/<name>.md`). */
  path: string;
  /**  File name only, for the preview header. */
  file_name: string;
  /**  Markdown source of the plan. */
  body: string;
};

export type PrSyncCompleted = {
  synced_count: number;
};

export type PrepareTaskResult = {
  task_id: string;
  task_run_id: string;
  branch: string;
};

export type ProjectOption = {
  id: string;
};

export type RunTaskResult = {
  task_id: string;
  task_run_id: string;
  runspace_id: string;
  cwd: string;
  env: [string, string][];
  initial_command: string;
};

export type TaskBench = {
  task_id: string;
  runspace_id: string;
  cwd: string;
  created: boolean;
  env: [string, string][];
};

export type TaskCreated = {
  task_id: string;
  title: string;
};

export type TaskRunStatus =
  | "setting_up"
  | "prepared"
  | "running"
  | "waiting_for_user"
  | "stopped"
  | "failed";

export type TaskRunStatusChanged = {
  task_id: string;
  task_run_id: string;
  status: TaskRunStatus;
};

export type TaskRunWaitReason =
  | "ask_user_question"
  | "exit_plan_mode"
  | "permission_request"
  | "awaiting_prompt";

export type TaskStatus = "ready" | "in_progress" | "closed";

export type TaskSummaryRow = {
  id: string;
  title: string;
  project: string | null;
  github_issue_number: number | null;
  github_pull_requests: GithubPullRequestRef[];
  task_status: TaskStatus;
  task_run_status: TaskRunStatus | null;
  task_run_wait_reason: TaskRunWaitReason | null;
  has_plan: boolean;
  status: DisplayStatus;
  prepare_eligible: boolean;
  run_eligible: boolean;
  is_active: boolean;
  has_open_pull_request: boolean;
  branch: string | null;
  side_runs_running: number;
  side_runs_waiting_for_user: number;
  side_runs_failed: number;
};

export type TerminalRunspaceRow = {
  id: string;
  sort_order: number;
  tabs: TerminalTabRow[];
};

/**
 *  A durable shell/agent process session owned by the PTY daemon. UI tabs attach to and
 *  detach from sessions; only an explicit terminate kills the underlying process.
 */
export type TerminalSession = {
  id: string;
  runspace_id: string | null;
  /**
   *  The Workbench tab this session was created for. Burned into the child env as
   *  MONICA_TERMINAL_TAB_ID, so reattach prefers reusing it to keep hook claims valid.
   */
  tab_id: string | null;
  kind: TerminalSessionKind;
  cwd: string;
  shell: string;
  status: TerminalSessionStatus;
  pid: number | null;
  rows: number;
  cols: number;
  transcript_path: string | null;
  exit_code: number | null;
  started_at: string | null;
  last_seen_at: string | null;
  exited_at: string | null;
  created_at: string;
  updated_at: string;
};

export type TerminalSessionKind = "shell" | "agent" | "task" | "scratch";

export type TerminalSessionStatus =
  | "starting"
  | "running"
  | "detached"
  | "exited"
  | "lost"
  | "failed";

export type TerminalStateSnapshot = {
  runspaces: TerminalRunspaceRow[];
};

export type TerminalTabRow = {
  id: string;
  cwd: string;
  title: string;
  sort_order: number;
  terminal_session_id: string | null;
};

export type WorktreeInfo = {
  repo: string;
  branch: string;
};

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>,
): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
  try {
    return { status: "ok", data: await result };
  } catch (e) {
    if (e instanceof Error) throw e;
    return { status: "error", error: e as any };
  }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(
  name: string,
  serialize?: (payload: T) => unknown,
  deserialize?: (payload: any) => T,
) {
  const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) =>
    cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
  const mapPayload = (payload: T) => (serialize ? serialize(payload) : payload);

  const base = {
    listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
    once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
    emit: ((payload: T) =>
      __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
  };

  const fn = (
    target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window,
  ) => ({
    listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
    once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
    emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>,
  });

  return Object.assign(fn, base);
}
