// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
  clipboardWriteImage: (path: string) =>
    typedError<null, string>(__TAURI_INVOKE("clipboard_write_image", { path })),
  ptySpawn: (id: string, cwd: string, rows: number, cols: number, env: [string, string][] | null) =>
    typedError<null, string>(__TAURI_INVOKE("pty_spawn", { id, cwd, rows, cols, env })),
  ptyWrite: (id: string, data: string) =>
    typedError<null, string>(__TAURI_INVOKE("pty_write", { id, data })),
  ptyResize: (id: string, rows: number, cols: number) =>
    typedError<null, string>(__TAURI_INVOKE("pty_resize", { id, rows, cols })),
  ptyKill: (id: string) => typedError<null, string>(__TAURI_INVOKE("pty_kill", { id })),
  terminalLoadState: () =>
    typedError<TerminalStateSnapshot, string>(__TAURI_INVOKE("terminal_load_state")),
  terminalSaveState: (state: TerminalStateSnapshot) =>
    typedError<null, string>(__TAURI_INVOKE("terminal_save_state", { state })),
  listTaskSummaries: () =>
    typedError<TaskSummaryRow[], string>(__TAURI_INVOKE("list_task_summaries")),
  getBoardColumns: () => __TAURI_INVOKE<BoardColumn[]>("get_board_columns"),
  listProjects: () => typedError<ProjectEntry[], string>(__TAURI_INVOKE("list_projects")),
  trackGithubIssue: (repo: string, number: number) =>
    typedError<TrackIssueResult, string>(__TAURI_INVOKE("track_github_issue", { repo, number })),
  listBenchRunspaceMap: () =>
    typedError<[string, string][], string>(__TAURI_INVOKE("list_bench_runspace_map")),
  taskShellEnv: (taskId: string) =>
    typedError<[string, string][], string>(__TAURI_INVOKE("task_shell_env", { taskId })),
  openBench: (taskId: string) =>
    typedError<TaskBench, string>(__TAURI_INVOKE("open_bench", { taskId })),
  prepareTask: (taskId: string) =>
    typedError<PrepareTaskResult, string>(__TAURI_INVOKE("prepare_task", { taskId })),
  runTask: (taskId: string) =>
    typedError<RunTaskResult, string>(__TAURI_INVOKE("run_task", { taskId })),
};

/* Types */
export type BoardColumn = {
  key: string;
  label: string;
  statuses: DisplayStatus[];
};

export type DisplayStatus =
  | "inbox"
  | "ready"
  | "in_progress"
  | "setting_up"
  | "prepared"
  | "running"
  | "waiting_for_user"
  | "stopped"
  | "failed"
  | "done";

export type GithubPullRequestRef = {
  repo: string | null;
  number: number;
  url: string | null;
  status: string | null;
};

export type PrepareTaskResult = {
  task_id: string;
  task_run_id: string;
  branch: string;
};

export type ProjectEntry = {
  repo: string;
  name: string;
};

export type RunTaskResult = {
  task_id: string;
  task_run_id: string;
  runspace_id: string;
  cwd: string;
  env: [string, string][];
  initial_command: string;
};

export type TaskBench = {
  task_id: string;
  runspace_id: string;
  cwd: string;
  created: boolean;
  env: [string, string][];
};

export type TaskRunStatus =
  | "setting_up"
  | "prepared"
  | "running"
  | "waiting_for_user"
  | "stopped"
  | "failed";

export type TaskRunWaitReason = "ask_user_question" | "exit_plan_mode";

export type TaskStatus = "inbox" | "ready" | "in_progress" | "done";

export type TaskSummaryRow = {
  id: string;
  title: string;
  project: string | null;
  github_issue_number: number;
  github_pull_requests: GithubPullRequestRef[];
  task_status: TaskStatus;
  task_run_status: TaskRunStatus | null;
  task_run_wait_reason: TaskRunWaitReason | null;
  status: DisplayStatus;
  branch: string | null;
};

export type TerminalRunspaceRow = {
  id: string;
  sort_order: number;
  is_active: boolean;
  tabs: TerminalTabRow[];
};

export type TerminalStateSnapshot = {
  runspaces: TerminalRunspaceRow[];
};

export type TerminalTabRow = {
  id: string;
  cwd: string;
  title: string;
  sort_order: number;
  is_active: boolean;
};

export type TrackIssueResult = {
  task_id: string;
  title: string;
};

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>,
): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
  try {
    return { status: "ok", data: await result };
  } catch (e) {
    if (e instanceof Error) throw e;
    return { status: "error", error: e as any };
  }
}
