// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
  clipboardWriteImage: (path: string) =>
    typedError<null, string>(__TAURI_INVOKE("clipboard_write_image", { path })),
  ptySpawn: (id: string, cwd: string, rows: number, cols: number) =>
    typedError<null, string>(__TAURI_INVOKE("pty_spawn", { id, cwd, rows, cols })),
  ptyWrite: (id: string, data: string) =>
    typedError<null, string>(__TAURI_INVOKE("pty_write", { id, data })),
  ptyResize: (id: string, rows: number, cols: number) =>
    typedError<null, string>(__TAURI_INVOKE("pty_resize", { id, rows, cols })),
  ptyKill: (id: string) => typedError<null, string>(__TAURI_INVOKE("pty_kill", { id })),
  terminalLoadState: () =>
    typedError<TerminalStateSnapshot, string>(__TAURI_INVOKE("terminal_load_state")),
  terminalSaveState: (state: TerminalStateSnapshot) =>
    typedError<null, string>(__TAURI_INVOKE("terminal_save_state", { state })),
};

/* Types */
export type TerminalRunspaceRow = {
  id: string;
  sort_order: number;
  is_active: boolean;
  tabs: TerminalTabRow[];
};

export type TerminalStateSnapshot = {
  runspaces: TerminalRunspaceRow[];
};

export type TerminalTabRow = {
  id: string;
  cwd: string;
  title: string;
  sort_order: number;
  is_active: boolean;
};

/* Tauri Specta runtime */
async function typedError<T, E>(
  result: Promise<T>,
): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
  try {
    return { status: "ok", data: await result };
  } catch (e) {
    if (e instanceof Error) throw e;
    return { status: "error", error: e as any };
  }
}
