[package]
name = "monica-storage-sqlite"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
monica-application.workspace = true
monica-domain.workspace = true
monica-paths.workspace = true
anyhow.workspace = true
log.workspace = true
rusqlite.workspace = true
rusqlite_migration.workspace = true
serde_json.workspace = true
