// This file is auto-generated by specta-typescript. Do not edit manually.
// Regenerate with: cargo test -p monica-web --lib tests::export_web_types -- --exact

// This file has been generated by Specta. Do not edit this file manually.
export type DailyNoteCount = {
  date: string;
  count: number;
};

export type Explanation = {
  id: string;
  title: string;
  summary: string | null;
  mode: ExplanationMode;
  provider_session_id: string;
  terminal_session_id: string;
  created_at: string;
  repo_name: string | null;
};

export type ExplanationMode = "diff" | "topic";

export type Note = {
  id: string;
  title: string | null;
  kind: NoteKind;
  project_id: string | null;
  /**  ProseMirror doc。TS 側でも opaque に扱うので unknown で export する。 */
  content: unknown;
  date: string;
  created_at: string;
  updated_at: string;
};

export type NoteKind = "essay" | "journaling" | "memo";

export type NotePage = {
  items: NoteSummary[];
  has_more: boolean;
};

export type NoteSummary = {
  id: string;
  title: string | null;
  kind: NoteKind;
  project_id: string | null;
  preview: string | null;
  date: string;
  created_at: string;
  updated_at: string;
};

export type ProjectOption = {
  id: string;
};

export type UpdateNote = {
  title: string | null;
  kind: NoteKind;
  project_id: string | null;
  content: unknown;
};
