// This file is auto-generated by specta-typescript. Do not edit manually.
// Regenerate with: cargo test -p monica-web --lib tests::export_web_types -- --exact

// This file has been generated by Specta. Do not edit this file manually.
/**  A stored image asset, returned by the upload / import routes. */
export type Asset = {
  id: string;
  url: string;
};

/**
 *  ⌥N（/projects）の新規 project note 作成リクエスト。project_id は "owner/repo" 形式で
 *  スラッシュを含むため path ではなく body で渡す。
 */
export type CreateProjectNote = {
  project_id: string;
};

export type DailyNoteCount = {
  date: string;
  count: number;
};

export type EssayStatus = "writing" | "finished";

export type Explanation = {
  id: string;
  title: string;
  summary: string | null;
  mode: ExplanationMode;
  provider_session_id: string;
  terminal_session_id: string;
  created_at: string;
  repo_name: string | null;
};

export type ExplanationMode = "diff" | "topic";

/**  Request body for importing an external image URL into the local asset store. */
export type ImportAsset = {
  url: string;
};

export type LinkPreview = {
  url: string;
  title: string | null;
  description: string | null;
  image: string | null;
  favicon: string | null;
  site_name: string | null;
};

export type Note = {
  id: string;
  kind: NoteKind;
  /**  ProseMirror doc。TS 側でも opaque に扱うので unknown で export する。 */
  content: unknown;
  date: string;
  created_at: string;
  updated_at: string;
};

/**
 *  synced block（transclusion）の解決結果。元 note の blockContainer subtree の
 *  ProseMirror JSON。TS 側でも opaque に扱う。
 */
export type NoteBlock = {
  block: unknown;
};

export type NoteKind =
  | { kind: "project"; project_id: string; title: string }
  | { kind: "daily" }
  | {
      kind: "essay";
      title: string;
      status: EssayStatus;
      /**
       *  ⌃Q・コンテキストメニューが次に送る status（`EssayStatus::toggled` の結果）。
       *  遷移規則を domain に閉じるため、フロントは二値判定せずこれをそのまま送る。
       */
      next_status: EssayStatus;
    };

/**
 *  wiki link（`[[`）の検索候補・解決結果。表示名の導出規則は domain の
 *  `NoteKind::display_name` にあり、フロントは受け取った文字列を表示するだけ。
 */
export type NoteMention = {
  id: string;
  display_name: string;
  /**  検索 dropdown のサブラベル。解決（単一取得）では返さない。 */
  preview: string | null;
};

export type NotePage = {
  items: NoteSummary[];
  has_more: boolean;
};

export type NoteSummary = {
  id: string;
  kind: NoteKind;
  preview: string | null;
  date: string;
  created_at: string;
  updated_at: string;
};

export type NotesSettings = {
  day_boundary_hour: number;
};

export type NotesToday = {
  /**  day boundary 設定を適用した logical date（`YYYY-MM-DD`）。 */
  date: string;
};

export type ProjectOption = {
  id: string;
  name: string;
};

/**  essay status 変更リクエスト（⌃Q）。トグルではなく冪等な明示 set。 */
export type SetEssayStatus = {
  status: EssayStatus;
};

/**  autosave の置換 payload。kind の変更は POST /api/notes/{id}/kind 専用で、ここには載らない。 */
export type UpdateNote = {
  /**  Essay の title 全置換。null = 触らない。essay 以外の note では無視される。 */
  title: string | null;
  content: unknown;
};
