// This file is auto-generated by specta-typescript. Do not edit manually.
// Regenerate with: cargo test -p monica-web --lib tests::export_web_types -- --exact

// This file has been generated by Specta. Do not edit this file manually.
export type Explanation = {
  id: string;
  title: string;
  mode: ExplanationMode;
  provider_session_id: string;
  terminal_session_id: string;
  created_at: string;
  repo_name: string | null;
};

export type ExplanationMode = "diff" | "topic";
